export enum CartActionTypes {
  "CART_ADD_ITEM" = "CART_ADD_ITEM",
  "CART_REMOVE_ITEM" = "CART_REMOVE_ITEM",
  "CART_SAVE_SHIPPING" = "CART_SAVE_SHIPPING",
  "CART_SAVE_PAYMENT" = "CART_SAVE_PAYMENT",
}
