export enum ProductActionTypes {
  "PRODUCT_LIST_REQUEST" = "PRODUCT_LIST_REQUEST",
  "PRODUCT_LIST_SUCCESS" = "PRODUCT_LIST_SUCCESS",
  "PRODUCT_LIST_FAIL" = "PRODUCT_LIST_FAIL",

  "PRODUCT_DETAILS_REQUEST" = "PRODUCT_DETAILS_REQUEST",
  "PRODUCT_DETAILS_SUCCESS" = "PRODUCT_DETAILS_SUCCESS",
  "PRODUCT_DETAILS_FAIL" = "PRODUCT_DETAILS_FAIL",

  "PRODUCT_SAVE_REQUEST" = "PRODUCT_SAVE_REQUEST",
  "PRODUCT_SAVE_SUCCESS" = "PRODUCT_SAVE_SUCCESS",
  "PRODUCT_SAVE_FAIL" = "PRODUCT_SAVE_FAIL",

  "PRODUCT_DELETE_REQUEST" = "PRODUCT_DELETE_REQUEST",
  "PRODUCT_DELETE_SUCCESS" = "PRODUCT_DELETE_SUCCESS",
  "PRODUCT_DELETE_FAIL" = "PRODUCT_DELETE_FAIL",

  "PRODUCT_REVIEW_SAVE_REQUEST" = "PRODUCT_REVIEW_SAVE_REQUEST",
  "PRODUCT_REVIEW_SAVE_SUCCESS" = "PRODUCT_REVIEW_SAVE_SUCCESS",
  "PRODUCT_REVIEW_SAVE_FAIL" = "PRODUCT_REVIEW_SAVE_FAIL",
  "PRODUCT_REVIEW_SAVE_RESET" = "PRODUCT_REVIEW_SAVE_RESET",
}
